# ----------------------------------------------------------------------------
#
# Package             : spring-boot
# Source Repo         : https://github.com/spring-projects/spring-boot
# Travis Job Link     : https://travis-ci.com/github/asellappen/spring-boot/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
dist: focal

language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk15
  - oraclejdk11
os:
  - linux
arch:
    - amd64
    - ppc64le
script :
    - travis_wait 30 ./gradlew build
    - ./gradlew checks
    - travis_wait 30 ./gradlew clean test
    - ./gradlew intTest
